# Generated by Django 3.0.2 on 2020-02-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='categories',
        ),
    ]
