version: '3'
volumes:
  pgdata:
  staticfiles:
services:
  python: &python
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    volumes:
      - ./home_budget:/home_budget
      - staticfiles:/staticfiles
    ports:
    - 8000:8000
    command: gunicorn -w 4 home_budget.wsgi -b 0.0.0.0:8000

  postgres:
    image: postgres:12.2-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: home_budget
      POSTGRES_PASSWORD: coderslab
    volumes:
    - pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
    - staticfiles:/staticfiles
    ports:
    - 80:80

  rabbitmq:
    image: rabbitmq:3.8-alpine

  celery_worker:
      <<: *python
      command: celery -A home_budget worker --loglevel=info
      ports:
        []
      depends_on:
        - rabbitmq
        - postgres

  celery_beat:
    <<: *python
    command: celery -A home_budget beat --loglevel=info
    ports:
      []
    depends_on:
      - rabbitmq
      - postgres